name: Space Game Web Project

trigger:
- none

pool:
 name: Azure Pipelines
 vmImage: 'windows-latest'

variables:
 buildConfiguration: 'Release'

steps:
- script: echo 'Hi this is Space Game Pipeline'