name: Space Game Web 

trigger:
- none

pool:
 name: Azure Pipelines
 vmImage: ubuntu-latest

variables:
 buildConfiguration: 'Release'

steps:
- script: echo 'Hi this is Space Game Pipeline'